---
Dear User: Please delete this line after you have finished setting up the config file.

# MySQL database setup
# You must use the same database and schema for all your plugins.
# The user used for hormones should have access to LOCK, CREATE, SELECT, INSERT, UPDATE and DELETE all tables in the schema.
mysql:
  host: 127.0.0.1
  username: root
  password: ""
  schema: hormones
  port: 3306
  socket: ""

# Localized information for this server
localize:
  # The type name of the server. Can be anything you want.
  # If balancer is enabled, players may be transferred to other servers of the same organ (case-insensitive) if server full.
  # Organ names should only consist of alphabets, numbers and hyphens [A-Za-z0-9-] to fit as command arguments, command names and permission names
  organ: normal
  # Set a unique name for this server, merely for displaying to users. Writing "auto" will be replaced by the server IP + port.
  # If you don't wish to make the server IP so obvious, you may use other
  name: auto
  # replace this with a DNS address that points to this server. Otherwise this will be replaced by an automatically detected external IP.
  # "address: auto" may not work if an IPv6 address is reported by online services.
  address: auto

# The kidney cleans old hormones.
# Since hormones are only used as a temporary medium of communication among servers in your network,
# the kidney should be operated regularly to prevent the database from storing a large amount of unneeded data.
# You may only want to disable the kidney for debug purposes.
# You might only need to enable kidney in any one of the servers in your network, but it doesn't hurt to enable in all.
# Enabling the kidney on all servers should not have notable negative impact on server performance.
kidney:
  enabled: true # whether to enable the kidney.
  interval: 600 # frequency to delete old hormones, in seconds
  expiry: 300 # number of seconds that hormones should stay in blood before being deleted

# Commands named after the organs that users can use to transfer to the most empty server of that tissue
# They will have permission nodes
oragnicTransfer:
  enabled: true

balancer:
  # This will only prevent transferring players to other tissues. Other tissues of the same organ ID may still transfer players to this tissue.
  enabled: true
  # Normal number of slots. Special players can bypass this limit but are still limited by the max-players in server.properties
  # If the soft limit is reached, normal players will be transferred to another server with the most empty slots.
  playerSoftLimit: 18
  # List of players (usernames, case-insensitive) who can bypass the soft limit.
  exemptPlayers:
  - Steve

# Ensures that no two logged-in players on the network will have the same name at the same moment
singleSession:
  # Action to do if there is collision. Possible values:
  #     off: Disable singleSession
  #     bump: Disallow login if a player of such name is already logged in in the network (in any organs, any tissues)
  #     push: Kick any other players if the condition in singleSession.pushUpon is met
  #     ip-push: push if both players have the same IP, bump if different IP

  # IMPORTANT: Make sure you use the same setttings on all network servers.
  mode: off

  # The auth plugin integration to use
  # This will be used to detect whether a player is online and logged in.
  # Possible values: none, SimpleAuth, ServerAuth, HereAuth, PiggyAuth
  # If "none" is chosen, player is considered "logged in" as long as the player is connected and remains online (even before being spawned)
  authIntegration: none

# Disallow clients to join this server unless transferred from another server in the network
## To select an appropriate transferOnly.mode, it is important to understand the transferOnly notification mechanism.
## Take the situation as "Server A wants to transfer Client to Server B".
##
###       +----->-----[Vein]------>------MySQL----->-----[Artery]----->----+
###       ^                                                                v
###    Server A                                                        Server B <----------+
###       v                                                                ^             [Join]
###       +--->--[TransferPacket]--->---Client----->-----[Login]----->-----+------->-------+
##
## Server A sends a signal through [Vein] to MySQL to notify that the client is being transferred to Server B,
## and Server B downloads the signal through [Artery] from MySQL.
## Server A sends a [TransferPacket] to Client, then the Client will [Login] in Server B.
## After a long "Building terrain" screen, the Client will [Join] in Server B.
##
## "Vein" is like throwing a ball (the Hormones signal) into a pond.
## "Artery" is like sinking a bucket into the pond, let the ball flow into it and then pulling out the bucket.
## Server B automatically repeats the cycle of sinking the bucket and pulling it.
##
## If transferOnly.asyncDeclaration is set to false, the server may lag (usually for a very short time, and users won't
## notice it; check "vein up time" with /hormones command) but ensures that the ball is in the pond before sending the
## TransferPacket, reducing the chance that the "Client" (lower) pathway happens faster than the "MySQL" (upper) pathway
## and hence the client getting kicked on Server B.
## Otherwise, they happen together.
## You may want to set it to true on servers that have a lot of transfers (e.g. "hub" servers).
##
## For transferOnly.mode:
### off: no need to check for transfers
### login: check if the ball is in the last few buckets
### login.sync: same as "login", but if check fails, additionally sink a new bucket, pull it out, and check if the ball
###             is there. may lag (usually for a very short time, and users won't notice it; check "artery net time"
###             with /hormones command), but won't lag if the ball is in the automatically pulled buckets before the login.
### diastole.single: "Diastole" refers to pulling back the bucket. This option will allow all clients to connect and
###                  start downloading chunks, resource packs, etc., and transfer will be checked immediately when the
###                  currently sunk bucket is pulled back.
### diastole.double: Same as diastole.single, except that it is checked in both the first and second pulling-back of the
###                  bucket.
### join: same as "login", except that it checks when the player spawns, not when the player just connects.
transferOnly:
# Settings for Server A
  asyncDeclaration: false

# Settings for Server B
  # available options: off, login, login.sync, diastole.single, diastole.double, join
  mode: off
  # Players logging in from these IP addresses will be exempted from this limit
  exemptAddresses:
  - 127.0.0.1
  # Possible address names that players can join this server with /transfer
  # localize.address is automatically added
  aka:
  # examples:
#  - server.pmmp.io       # assuming the port from server.properties
#  - server.pmmp.io:19135
...
